### ISSUE TITLE
customize error handler

### ISSUE THREAD

**Issue by andrcher** [newsiberian/apollo-link-token-refresh#1]
If server returns non ok response, I can see only error in console. Make customize error handler, please.

**Comment by newsiberian** [comment]
Hi, does latest changes solved your issue?

**Comment by andrcher** [comment]
Hi, thank's for commit, but it's not what I want.
If there is an error, I want to call my own function, for example, logout user.

P.S. if server return bad response without body, script failed.

**Comment by newsiberian** [comment]
Could you try a new version?

**Comment by andrcher** [comment]
In version 0.1.0 it works. Thank's.
