### ISSUE TITLE
Type 'TokenRefreshLink' is missing the following properties from type 'ApolloLink': onError, setOnError ts(2739)

### ISSUE THREAD

**Issue by miller-productions** [newsiberian/apollo-link-token-refresh#20]
Hi there,

Just wondering if anyone has encountered this issue.

When trying to use TokenRefreshLink, I get the following error when building up the link property..

    Type 'TokenRefreshLink' is missing the following properties from type 'ApolloLink': onError, setOnError ts(2739)

```
const refreshTokenLink = new TokenRefreshLink({
// etc... <omitted here for brevity>
// set proper values for 
accessTokenField:
isTokenValidOrUndefined:
fetchAccessToken:
handleFetch:
handleError:
```

I also build up a basic set of other links

Then...

    // compose the links in sequence 
    const link = from([refreshTokenLink, errorLink, authLink, httpLink]);
                                  ^^^
                              error occurs here

------------

Using the following

    "apollo-link-token-refresh": "^0.2.7",
    "@apollo/client": "^3.0.0-beta.44",
    "@apollo/link-context": "^2.0.0-beta.3",
    "@apollo/link-error": "^2.0.0-beta.3",

-------------

I have found the following similar type of issue over [here](https://github.com/apollographql/apollo-link/issues/538) and also [here](https://github.com/apollographql/apollo-link/issues/1258).

I have tried the following:

* downgrading to an older version of "@apollo/client": "^3.0.0-beta.37". (didn't solve it)
* upgrading to a newer version "@apollo/client": "^3.0.0-beta.48", (made it worse, got additional errors)
* casting `(new TokenRefreshLink({` etc `as unknown) as ApolloLink`

**Comment by maryschmidt** [comment]
I'm getting the same type error instantiating a new client using `apollo-boost`. Tried the same steps to resolve to no avail.

**Comment by alexbarksdale** [comment]
@miller-productions @maryschmidt A temporary solution that I'm using is just simply casting the `new TokenRefreshLink({....})` as `any`.

Example:
```ts
....
new TokenRefreshLink({
    accessTokenField: '....',
    isTokenValidOrUndefined: () => {....},
    fetchAccessToken: () => {....},
    handleFetch: (accessToken) => {....},
    handleError: (err) => {....},
}) as any,
....
```

**Comment by miller-productions** [comment]
Issue appears to be resolved following #18 

I can confirm that I am no longer seeing the issue with

```
"@apollo/client": "^3.0.0-beta.48",
"apollo-link-token-refresh": "^0.3.1",
```

**Comment by ArtGurianov** [comment]
@miller-productions The error still appears with the latest @apollo/client version 'rc-0'....

**Comment by miller-productions** [comment]
Reports in the wild this is still occurring using @apollo/client version 'rc-0'.

Is anyone seeing this?

**Comment by chrisjaimes** [comment]
**Types of property 'split' are incompatible.**
```
"apollo-client": "^2.6.10",
 "apollo-link-token-refresh": "^0.3.1",
```

Fails here at `refreshLink`
```   link: from([authMiddleware, logoutLink, refreshLink, http]),```

**Comment by newsiberian** [comment]
@chrisjaimes , version 0.3.x is only compatible w/ apollo 3

**Comment by onpaws** [comment]
> Reports in the wild this is still occurring using @apollo/client version 'rc-0'.
> 
> 
> 
> Is anyone seeing this?
> 
> 

I was able to resolve this by carefully ensuring everything in package.json about Apollo was at v3, _removing yarn.lock_, and reinstalling. Stubborn one. Hope this helps!

**Comment by chrisjaimes** [comment]
@newsiberian thanks, I just downgraded to 0.2.5 but I'm still getting the following error:
```
Type 'TokenRefreshLink<string>' is missing the following properties from type 'ApolloLink': split, concat
```
unless... I do `as any`

**Comment by eDubrovsky** [comment]
> Reports in the wild this is still occurring using @apollo/client version 'rc-0'.
> 
> Is anyone seeing this?

Confirm this error with @apollo/client version `3.0.rc-2`

**Comment by miller-productions** [comment]
Closing this - confirmed it is no longer an issue in the latest versions of apollo-link-token-refresh and @apollo/client.
