### ISSUE TITLE
Incorrect typing of HandleFetch

### ISSUE THREAD

**Issue by Faithfinder** [newsiberian/apollo-link-token-refresh#21]
https://github.com/newsiberian/apollo-link-token-refresh/blob/4f8d6c92addde76edd12121417ae99735d5881fe/src/tokenRefreshLink.ts#L14

The argument for HandleFetch is not necessarily a string, but the interface restricts it right now.

**Comment by newsiberian** [comment]
Can you, please, make a PR for this?
