### ISSUE TITLE
Incompatible with apollo v3.0.0-rc.0

### ISSUE THREAD

**Issue by ArtGurianov** [newsiberian/apollo-link-token-refresh#23]
Argument of type 'TokenRefreshLink' is not assignable to parameter of type 'ApolloLink | RequestHandler'.
  Type 'TokenRefreshLink' is not assignable to type 'ApolloLink'.
    Types of property 'split' are incompatible.

Please update.

**Comment by benyou1969** [comment]
@ArtGurianov  did you find solution to this issue?

**Comment by benyou1969** [comment]
well i found this one https://github.com/newsiberian/apollo-link-token-refresh/issues/20#issuecomment-633207341
but it doesn't seem like a real solution : (
