### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by chrisjaimes** [newsiberian/apollo-link-token-refresh#24]
I keep getting this error:
`Cannot read property 'data' of undefined`

I tried printing out both the `body` and `_this.accessTokenField` in the `tokenRefreshLink.js` file
```
console.log('_this.accessTokenField', _this.accessTokenField)
console.log('body', body)
```
the output is `_this.accessTokenField access_token` and `body undefined` respectively.

That `body` variable is accessed with a `data` property in the tokenRefreshLink.js but body is undefined. The response I send from the backend is an object with the `access_token` property with a string value which is the refresh token.

This is how I fetch the access token:
```
...

fetchAccessToken: () => {
      return fetch('http://localhost:4000/refresh_token', {
        method: 'POST',
        credentials: 'include',
      });
    }
...

```

Any ideas? What is expected from that `body` variable that is undefined and keeps failing in my implementation?

**Comment by chrisjaimes** [comment]
related to #11 
Solved by removing `handleResponse`

**Comment by fabrianibrahim** [comment]
> related to #11 Solved by removing `handleResponse`

what if I want to use handleResponse ?
