### ISSUE TITLE
"@apollo/client" as Peer Dependency? 

### ISSUE THREAD

**Issue by valeeum** [newsiberian/apollo-link-token-refresh#36]
I think it's better to have "@apollo/client" as a peerDependency instead of a straight up dependency.    What do you think?

**Comment by newsiberian** [comment]
good point. Initially it was copy-pasted to deps as same as packages from `apollo-link`

**Comment by newsiberian** [comment]
could you please create a PR?

**Comment by newsiberian** [comment]
closed via #43
