### ISSUE TITLE
parseAndCheckResponse assumes too much about underlying response

### ISSUE THREAD

**Issue by moltar** [newsiberian/apollo-link-token-refresh#4]
https://github.com/newsiberian/apollo-link-token-refresh/blob/6a56931c2392b56f57286507948edb45ab234a42/src/tokenRefreshLink.ts#L44

Assumes response has a `.text()` method, but this is not always the case.

1. Using `request-promise` module will return data directly without a response.
2. Using `ApolloClient` would return a data object without response object.

I think this should either not assume anything or let user configure that handler.

**Comment by newsiberian** [comment]
Hi, I think we could make this customizable, like the rest of the handlers, but I do not have enough time at the moment

**Comment by newsiberian** [comment]
Hi, I've added an ability to use custom repsonse handler with latest commit. Please, try it out.

**Comment by moltar** [comment]
Thank you! :)
