### ISSUE TITLE
Confusing guidelines

### ISSUE THREAD

**Issue by Spark3000** [newsiberian/apollo-link-token-refresh#40]
> Indicates the current state of access token expiration. If token not yet expired or user doesn't have a token (guest) true should be returned

Please correct me if I'm wrong but for `isTokenValidOrUndefined` method, it should return `true` if a user doesn't "need" a token. Contrary to the method description, if they don't **have a token** (but do need one) then **false** should be returned. 

Am I right in thinking a more explanatory name for the method might be `isTokenValid` or `tokenRefreshNotNeeded` (bit weird). Would be better to flip the response and call it: `shouldTokenRefresh`

or at least the description should be:
_"Indicates the current state of access token expiration. If the token is not yet expired or the user does not require a token (guest), then `true` should be returned"_

Sorry - I just was really confused by this for ages 😕

**Comment by newsiberian** [comment]
Hi, @Spark3000. Thanks for pointing this. Really naming is a problem in this case. I agree that it is not perfect. `isTokenValid`, imho, not reflects case when user don't need token at all; `tokenRefreshNotNeeded`, I agree, looks weird.

I think your description is perfect. Could you, please, make a PR, and we apply it?

**Comment by Spark3000** [comment]
Sure :) Done.
