### ISSUE TITLE
graphql peer dependenceies

### ISSUE THREAD

**Issue by liushh** [newsiberian/apollo-link-token-refresh#47]
Hi, 

When I run npm install with my current app I get the following error:

npm ERR! While resolving: nimbus@0.1.8
npm ERR! Found: graphql@16.2.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"^16.2.0" from the root project
npm ERR!   peer graphql@"^14.0.0 || ^15.0.0 || ^16.0.0" from @apollo/client@3.5.8
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"^3.4.7" from the root project
npm ERR!     peer @apollo/client@"^3.0.0" from apollo-link-token-refresh@0.3.3
npm ERR!     node_modules/apollo-link-token-refresh
npm ERR!       apollo-link-token-refresh@"^0.3.3" from the root project
npm ERR!   1 more (subscriptions-transport-ws)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0" from apollo-link-token-refresh@0.3.3
npm ERR! node_modules/apollo-link-token-refresh
npm ERR!   apollo-link-token-refresh@"^0.3.3" from the root project
npm ERR!

General Info:
npm: v7.21.1
node: v16.8.9

I believe this issue is not specific to my own app. 

Do you think we can update the peer dependencies for `apollo-link-token-refresh` to adopt the latest version of graphql? 

thanks,
Liusha

**Comment by newsiberian** [comment]
Hi, @liushh , thanks for report. I've updated version. Can you check?
