### ISSUE TITLE
How to Use Token Refresh Link w/ Context API?

### ISSUE THREAD

**Issue by kharithomas** [newsiberian/apollo-link-token-refresh#50]
_First_, thank you for the hard work on this package - it's been essential to the apps I've built.

A common practice is to use React context API to login, logout, and retrieve accessTokens for users.

With this package, I have opted to use just store my accessToken inside a global variable like so:

```
// authToken.js

let _accessToken = "";

export const setAccessToken = (accessToken = "") => {
  _accessToken = accessToken;
};

export const getAccessToken = () => {
  return _accessToken;
};
```

This typically works as I can rely on having separate screens to redirect the user to after login / logout to trigger component re-renders.

However, I am now using a modal for login / logout so I'd like to use the Context API to trigger re-rendering of the header and other components after the user logs in / out.

Since we are outside of a react component, the useContext can't be used here.

```
// index.js

const client = new ApolloClient({
  cache: new InMemoryCache({}),
  defaultOptions,
  link: ApolloLink.from([
    new TokenRefreshLink({
      accessTokenField: "token",
      isTokenValidOrUndefined: () => {
        const token = getAccessToken(); // how to use context here instead of global variable?
        if (!token) {
          return true;
        }

        try {
          const { exp } = jwtDecode(token);
          if (Date.now() >= exp * 1000) {
            return false;
          } else {
            return true;
          }
        } catch {
          return false;
        }
      },
     
      // ... rest of links
```

Is there a way I can provide the accessToken for the refreshLink and use Context API ?

**Comment by newsiberian** [comment]
hi, @kharithomas please take a look here #48

**Comment by kharithomas** [comment]
Thanks @newsiberian , this seems to address my issue as well.

**Comment by kharithomas** [comment]
@newsiberian Since my question was solved - you can close this one too. Thanks
