### ISSUE TITLE
Webpack warnings when building the package - Failed to parse source map 

### ISSUE THREAD

**Issue by FominSergiy** [newsiberian/apollo-link-token-refresh#60]
Hi there!

Running into a few warnings when the webpack builds our application. This does not stop the package from running, but rather a log warning.  The warnings relate to this issue: https://github.com/newsiberian/apollo-link-token-refresh/issues/54

(see below)
```
WARNING in ../../../node_modules/apollo-link-token-refresh/lib/queuing.js
Module Warning (from ../../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/SergiyFomin/work-space/QualityNow/node_modules/apollo-link-token-refresh/src/queuing.ts' file: Error: ENOENT: no such file or directory, open '/Users/SergiyFomin/work-space/QualityNow/node_modules/apollo-link-token-refresh/src/queuing.ts'

WARNING in ../../../node_modules/apollo-link-token-refresh/lib/tokenRefreshLink.js
Module Warning (from ../../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/SergiyFomin/work-space/QualityNow/node_modules/apollo-link-token-refresh/src/tokenRefreshLink.ts' file: Error: ENOENT: no such file or directory, open '/Users/SergiyFomin/work-space/QualityNow/node_modules/apollo-link-token-refresh/src/tokenRefreshLink.ts'
```

I looked into it and the problem appears to be because this repo stores typescript-compiled files in the same directory as the output bundle package - the `./lib`. Hence the tsc-compiled files throw these warnings.

I can see we need those compiled files to generate bundle, but we only need typescript definitions with the bundle.

almost as if we need to:
- run tsc compile to get files for the bundle
- bundle them
- run tsc compile again just to store the typescript definitions (`emitDeclarationOnly: true`)

```
./lib
  bundle.umd.js/
    bundle.umd.js.map
  queuing.d.ts.map
  queuing.js/                                     <-- throws warnings
    queuing.js.map                            <-- throws warnings
  tokenRefreshLink.d.ts.map
  tokenRefreshLink.js/                 <-- throws warnings
    tokenRefreshLink.js.map        <-- throws warnings  

```

**Question**

do you see the need to keep the `.js` files in the `./lib`, or typescript definitions together with the `bundle` should be enough?

**Comment by FominSergiy** [comment]
![Screenshot 2023-10-25 at 11 58 50 AM](https://github.com/newsiberian/apollo-link-token-refresh/assets/65659492/77e6efb3-b8cb-4f0b-bc90-e6d90ec7281c)

I kept only bundle and typescript definitions in my pulled npm package and it seems to be working.

**Comment by newsiberian** [comment]
Thanks for highlighting this. I've taken how apollo-client injects source content into source-maps. Could you please check version  `0.6.1-alpha.0` and let me know if it works for you?

**Comment by FominSergiy** [comment]
hello again! much appreciate the response, pulled the `0.6.1-alpha.0` version and it works! warnings are gone 😁 I will keep using `0.6.0` for now until the `0.6.1` is available.

great work!

**Comment by newsiberian** [comment]
v6.1.0 been released

**Comment by FominSergiy** [comment]
thanks!
