### ISSUE TITLE
Order with restLink

### ISSUE THREAD

**Issue by nazmeln** [newsiberian/apollo-link-token-refresh#62]
Hey,
Thanks for such a great package!
Could you please tell me what order it should be for the next links?
```
    link: ApolloLink.from([
        retryLink as unknown as ApolloLink,
        errorLink,
        authLink,
        restLink as unknown as ApolloLink,
        schemaLink,
    ]),
```

Many thanks!

**Comment by newsiberian** [comment]
Hi, thanks for that. I'm not aware of restLink and I think you have to figure the correct order our by yourself. Try to ask yourself, should the restLink logic be called when access token staled? In my setup authLink was first in the chain.
