### ISSUE TITLE
isTokenValidOrUndefined operation

### ISSUE THREAD

**Issue by EdwardNelson** [newsiberian/apollo-link-token-refresh#8]
Any chance the operation object can be passed to the isTokenValidOrUndefined function?

I am looking to read from the cache at this point. For example, to read my token from the cache.

**Comment by guiccbr** [comment]
This would help me too. I'm planning to send a simple PR soon with a proposal for this.

**Comment by da3monHunter** [comment]
@guiccbr  did u get through with it?

**Comment by juliangsibecas** [comment]
Any updates?

**Comment by justenau** [comment]
This got fixed with https://github.com/newsiberian/apollo-link-token-refresh/issues/49 and can be closed.
